# GitHub Secret Scanning Configuration
# Scan patterns for custom secret detection

version: 1

patterns:
  - name: Stacks Private Key
    type: private_key
    pattern: 'CREATOR_PRIVATE_KEY|DEPLOYER_PRIVATE_KEY\s*=\s*[a-f0-9]{40,}'
    
  - name: PINATA API Keys
    type: api_key
    pattern: 'PINATA_(API_KEY|SECRET_API_KEY)\s*=\s*\w+'
    
  - name: MongoDB Connection String
    type: database_connection
    pattern: 'mongodb://.*:.*@.*'
    
  - name: Master Encryption Key
    type: encryption_key
    pattern: 'CONTENT_ENCRYPTION_MASTER_KEY\s*=\s*\w+'
    
  - name: JWT/Webhook Secrets
    type: secret_key
    pattern: '(JWT_SECRET|WEBHOOK_SECRET|SESSION_SECRET)\s*=\s*\w+'

severity: high

ignorePatterns:
  - test
  - example
  - placeholder
  - change-me
